FROM continuumio/anaconda3

ADD requirements.txt .
RUN pip install -r requirements.txt

WORKDIR /dash/

#docker run -it --rm -p 8050:8050 -v $PWD:/dash dash python test-dash.py

#docker run -it --rm -p 8050:8050 -v $PWD:/dash --label carb-group=dashgroup dash python test-dash.py
